### ISSUE TITLE
macOS Ventura VM shared cache location

### ISSUE THREAD

**Issue by keith** [keith/dyld-shared-cache-extractor#4]
I'm not sure if this is a permanent change or just a VM detail, but I noticed in my macOS Ventura VM that the shared cache location is actually:

```
/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/...
```

There is also:

```
/System/Volumes/Preboot/Cryptexes/OS/System/DriverKit/System/Library/dyld/
```

Which seems to have a smaller subset of libraries potentially used at boot?

Just filing this in case others are looking for this info

**Comment by 0x3c3e** [comment]
@keith thanks
Also in case someone is trying it on Ventura, don't forget `DEVELOPER_DIR=/Applications/Xcode-beta.app`

**Comment by philipphofmann** [comment]
I updated my MacBook Air M1, and I can confirm the dyld location pointed out in https://github.com/dortania/OpenCore-Legacy-Patcher/issues/998#issuecomment-1163607808:
```
/System/Volumes/Preboot/{Ventura Preboot UUID}/cryptex1/current:
  - os.dmg
```
Maybe it makes sense to add this info to the ReadMe, @keith?

**Comment by keith** [comment]
@philipphofmann is that specifically for the dyld shared cache or for some other files? Or are you saying the paths I mentioned above should be in the readme now?

**Comment by philipphofmann** [comment]
I think the ReadMe should point out where the dyld shared cache location is. Currently, the ReadMe only points out `/System/Library/dyld/`. You have to navigate to this issue to find out where they are on macOS 13. I think the ReadMe should let you know where the dyld shared cache is on macOS 13.

I just added the info where I found the dyld cache on my MacBook Air M1.

**Comment by keith** [comment]
Yep makes sense, I was just confused about your path example above since it wasn't the path to the shared cache. I've submitted https://github.com/keith/dyld-shared-cache-extractor/pull/6
