### ISSUE TITLE
xcrun: error: SDK "phoneos" cannot be located

### ISSUE THREAD

**Issue by wrefactor** [keith/dyld-shared-cache-extractor#9]
Hi - thanks for sharing this code!  Just in case it helps anyone else, I got the following error having installed from homebrew:
```
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'PlatformPath' in SDK 'iphoneos'
error: failed to fetch Xcode path
```
I thought the problem was that it was looking for 'iphoneos' rather than 'macos', but eventually I realised that `xcodebuild -showsdks`, `xcrun --sdk macos`, etc, weren't working either.  Everything worked again after running `xcode-select -r` (as root) to reset my CLTs path.

**Comment by keith** [comment]
👍🏻
